#!/bin/bash
clear
echo -e "\e[1;31m"
echo ' _   _  ___    __  __  ___  ____  _____   ____  ____   ___  ____'
echo '| \ | |/ _ \  |  \/  |/ _ \|  _ \| ____| |  _ \|  _ \ / _ \/ ___|'
echo '|  \| | | | | | |\/| | | | | |_) |  _|   | | | | | | | | | \___ \'
echo '| |\  | |_| | | |  | | |_| |  _ <| |___  | |_| | |_| | |_| |___) |'
echo '|_| \_|\___/  |_|  |_|\___/|_| \_\_____| |____/|____/ \___/|____/'
echo '=================================================================='
echo
echo -e "\e[0m"
echo '	0 --> Exit'
echo '	1 --> Test the No More DDOS Agent'
echo '	2 --> Add an IP in the White List'
echo '	3 --> Show the actual Ban List'
echo '	4 --> Unban an IP'
echo '	5 --> Ban an IP'
echo '	6 --> Blank agent log'
echo '	7 --> Restore CRON'
echo '	8 --> Restore the default configuration'
echo
echo "Now choose :"

read n
case $n in
    0) clear;;
    1) clear && /usr/local/nmd/nmd-agent.sh;;
    2) clear && /usr/local/nmd/white-list/white-list.sh;;
    3) clear && /usr/local/nmd/scripts/show-ban.sh;;
    4) clear && /usr/local/nmd/scripts/unban.sh;;
    5) clear && /usr/local/nmd/scripts/ban.sh;;
    6) clear && /usr/local/nmd/scripts/reset-log.sh;;
    7) clear && /usr/local/nmd/nmd-agent.sh -c;;
    8) clear && /usr/local/nmd/scripts/default-config.sh;;
    *) /usr/local/nmd/scripts/error.sh;;
esac